---

- name: git clone ghuser.io's DB scripts
  git:
    repo: "https://{{ github_username }}:{{ github_password }}@github.com/ghuser-io/db.git"
    dest: /home/ubuntu/db/
    depth: 10

- name: npm install ghuser.io's DB scripts' deps
  command: npm install
  args:
    chdir: /home/ubuntu/db/

- name: Reset package-lock.json
  command: git reset --hard HEAD
  args:
    chdir: /home/ubuntu/db/

- name: Install fetchBot's dependencies
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - name: raven-bash
      version: 1.0
    - name: awscli
      version: 1.16.4
  become: True

- name: Configure raven-bash
  template:
    src: raven-bash.conf.j2
    dest: /etc/raven-bash.conf
  become: True

- name: Install fetchBot's other dependencies
  apt:
    name: jq
  become: True
